name: CI
on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.2.0'  # 指定 Node.js 版本
    - run: npm install
    - run: npm run upload